### ISSUE TITLE
Búsqueda de espacios aplicando filtros

### ISSUE THREAD

**Issue by EduardoGimeno** [UNIZAR-30249-2020-GRUPO02/Servidor-Aplicaciones#13]
Búsqueda de espacios aplicando los filtros establecidos. Estos filtros son edificio, tipo de espacio, capacidad, periodo, fecha inicio, fecha fin, días, hora de entrada, hora de salida, pizarra, cañón. buscar(BusquedaDTO busqueda): EspacioDTO[*]

**Comment by MegaGera** [comment]
En principio acabado. Si hay tiempo  darle una vuelta.
